# Generated by Django 4.2.5 on 2023-09-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('robot_model', models.CharField(max_length=2)),
                ('robot_version', models.CharField(max_length=2)),
                ('total_production', models.PositiveIntegerField()),
            ],
        ),
    ]
