# Generated by Django 4.2.5 on 2023-09-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_productionreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionReport',
        ),
    ]
