# Generated by Django 4.2.5 on 2023-09-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_delete_productionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
