# Generated by Django 4.2.5 on 2023-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robot_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
